### ISSUE TITLE
[Epic] Scraper 

### ISSUE THREAD

**Issue by a-camarillo** [BobaTalks/internship-tracker#65]
### Notes: 

- I imagine the bulk of the work will come from figuring out how to parse each respective job post since each site has a different structure to its posts
- Ideally we want a uniform structure of data to store in the database in order to avoid having a database table per company which wouldn't be terrible for now but likely won't scale. This means sending the data to the database might only be one task.

### Tasks:

Meta:
- [ ] Scrape job postings From Meta Careers Site
- [ ] Parse data from Meta job post
- [ ] Structure data
- [ ] Send data to database

Amazon:
- [ ] Scrape job postings From Amazon Careers Site
- [ ] Parse data from Amazon job post
- [ ] Structure data
- [ ] Send data to database

Netflix:
- [ ] Scrape job postings From Netflix Careers Site
- [ ] Parse data from Netflix job post
- [ ] Structure data
- [ ] Send data to database

Google:
- [ ] Scrape job postings From Google Careers Site
- [ ] Parse data from Google job post
- [ ] Structure data
- [ ] Send data to database

Apple:
- [ ] Scrape job postings From Apple Careers Site
- [ ] Parse data from Apple job post
- [ ] Structure data
- [ ] Send data to database

### To Discuss:
- How often do we expect this scraper to run? Can we determine the frequency internships can be posted?
- Is there data being expected that we cannot scrape/deliver?

**Comment by jwu910** [comment]
@lilyxmeng FYI, here's the story @a-camarillo set up to break up the scraping, we can use this to focus on the key parts for each company one at a time

**Comment by kpxwinter** [comment]
Note: We're not doing Microsoft so the goal is still to scrape 5 sites total
